[package]
name = "p0sticcio_bot"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
tokio = { version = "1.14.0", features = ["macros", "rt", "rt-multi-thread"] }
reqwest = { version = "0.11.6", features = ["cookies"] }
ingress_intel_rs = { git = "https://github.com/nappa85/ingress-intel-rs.git" }
lru_time_cache = "0.11"
once_cell = "1.8.0"
serde_json = "1.0.71"
tracing = "0.1.29"
tracing-subscriber = { version =  "0.3.1", features = ["env-filter"] }
