[package]
name = "p0sticcio_bot"
version = "0.12.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true

[dependencies]
chrono = "0.4.21"
futures-util = "0.3.21"
tokio = { version = "1.20.1", features = ["macros", "rt", "rt-multi-thread", "fs", "parking_lot"] }
reqwest = { version = "0.11.11", features = ["cookies"] }
ingress_intel_rs = { git = "https://github.com/nappa85/ingress-intel-rs.git" }
lru_time_cache = "0.11.11"
once_cell = "1.13.0"
rust_decimal = "1.26.1"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
serde_yaml = "0.9.4"
stream_throttle = "0.4.0"
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
