[package]
name = "p0sticcio_bot"
version = "0.13.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true

[dependencies]
chrono = "0.4.23"
futures-util = "0.3.26"
tokio = { version = "1.26.0", features = ["macros", "rt", "rt-multi-thread", "fs", "time"] }
reqwest = { version = "0.11.14", features = ["cookies"] }
ingress_intel_rs = { git = "https://github.com/nappa85/ingress-intel-rs.git" }
lru_time_cache = "0.11.11"
once_cell = "1.17.1"
rust_decimal = "1.28.1"
serde = { version = "1.0.154", features = ["derive"] }
serde_json = "1.0.94"
serde_yaml = "0.9.19"
stream_throttle = "0.4.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
