[package]
name = "p0sticcio_bot"
version = "0.5.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
futures-util = "0.3.17"
tokio = { version = "1.15.0", features = ["macros", "rt", "rt-multi-thread", "fs"] }
reqwest = { version = "0.11.7", features = ["cookies"] }
ingress_intel_rs = { git = "https://github.com/nappa85/ingress-intel-rs.git" }
lru_time_cache = "0.11.11"
once_cell = "1.9.0"
rust_decimal = "1.18.0"
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
serde_yaml = "0.8.23"
stream_throttle = "0.4.0"
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.3", features = ["env-filter"] }
