[package]
name = "p0sticcio_bot"
version = "0.15.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true

[dependencies]
chrono = "0.4.38"
futures-util = "0.3.30"
tokio = { version = "1.38.0", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "fs",
    "time",
] }
tokio-stream = "0.1.15"
reqwest = { version = "0.12.5", features = ["cookies"] }
ingress_intel_rs = { git = "https://github.com/nappa85/ingress-intel-rs.git" }
lru_time_cache = "0.11.11"
once_cell = "1.19.0"
rust_decimal = "1.35.0"
sea-orm = { version = "0.12.15", features = [
    "macros",
    "sqlx-mysql",
    "runtime-tokio-rustls",
] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
serde_yaml = "0.9.34"
stream_throttle = "0.5.1"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[dev-dependencies]
rust_decimal_macros = "1.34.2"
