[package]
name = "p0sticcio_bot"
version = "0.11.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true

[dependencies]
chrono = "0.4.19"
futures-util = "0.3.21"
tokio = { version = "1.19.2", features = ["macros", "rt", "rt-multi-thread", "fs", "parking_lot"] }
reqwest = { version = "0.11.11", features = ["cookies"] }
ingress_intel_rs = { git = "https://github.com/nappa85/ingress-intel-rs.git" }
lru_time_cache = "0.11.11"
once_cell = "1.13.0"
rust_decimal = "1.25.0"
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
serde_yaml = "0.8.25"
stream_throttle = "0.4.0"
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.14", features = ["env-filter"] }
