[package]
name = "p0sticcio_bot"
version = "0.14.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true

[dependencies]
chrono = "0.4.31"
futures-util = "0.3.29"
tokio = { version = "1.33.0", features = ["macros", "rt", "rt-multi-thread", "fs", "time"] }
reqwest = { version = "0.11.22", features = ["cookies"] }
ingress_intel_rs = { git = "https://github.com/nappa85/ingress-intel-rs.git" }
lru_time_cache = "0.11.11"
once_cell = "1.18.0"
rust_decimal = "1.32.0"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
serde_yaml = "0.9.27"
stream_throttle = "0.5.1"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
