[package]
name = "p0sticcio_bot"
version = "0.12.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true

[dependencies]
chrono = "0.4.22"
futures-util = "0.3.25"
tokio = { version = "1.21.2", features = ["macros", "rt", "rt-multi-thread", "fs", "parking_lot"] }
reqwest = { version = "0.11.12", features = ["cookies"] }
ingress_intel_rs = { git = "https://github.com/nappa85/ingress-intel-rs.git" }
lru_time_cache = "0.11.11"
once_cell = "1.15.0"
rust_decimal = "1.26.1"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.87"
serde_yaml = "0.9.13"
stream_throttle = "0.4.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
