[package]
name = "p0sticcio_bot"
version = "0.13.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true

[dependencies]
chrono = "0.4.23"
futures-util = "0.3.25"
tokio = { version = "1.23.0", features = ["macros", "rt", "rt-multi-thread", "fs", "time"] }
reqwest = { version = "0.11.13", features = ["cookies"] }
ingress_intel_rs = { git = "https://github.com/nappa85/ingress-intel-rs.git" }
lru_time_cache = "0.11.11"
once_cell = "1.16.0"
rust_decimal = "1.27.0"
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
serde_yaml = "0.9.14"
stream_throttle = "0.4.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
